name: Frontend CI/CD to ECR & EKS

on:
  push:
    branches:
      - main
    

permissions:
  id-token: write   # 🔥 REQUIRED FOR OIDC
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ OIDC-based AWS login (NO secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::077419561607:role/github-action-role
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 077419561607.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Frontend Image
        run: |
          docker build -t frontendapp ./Application-Code/frontend

      - name: Tag Image
        run: |
          docker tag frontendapp:latest \
          077419561607.dkr.ecr.us-east-1.amazonaws.com/frontendapp:latest

      - name: Push Image
        run: |
          docker push 077419561607.dkr.ecr.us-east-1.amazonaws.com/frontendapp:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eksdemo1

      - name: Deploy Frontend
        run: |
          kubectl apply -f Kubernetes-Manifests-file/Frontend/deployment.yaml